model_type: "classification"  # "classification" or "segmentation"
nb_layers: 8
layers_for_segmentation: [3, 5, 7]  # Indices are zero-indexed
embedding_dim: 40
nb_heads: 10
patch_side_length: 4
stride: 4
mlp_expansion: 4
