name: "CIFAR10"
nb_channels: 3
image_height: 32
image_width: 32
nb_classes: 10  # image-level classification classes (ImageNet)
nb_semantic_labels: 0  # pixel-level segmentation classes
training_validation_split: 0.9
