# Learning Multiple Layers of Features from Tiny Images, Alex Krizhevsky, 2009.
# https://www.cs.toronto.edu/~kriz/cifar.html
name: "CIFAR100"
task_type: "image_classification"
nb_channels: 3
image_height: 32
image_width: 32
nb_classes: 100  # image-level classification classes (ImageNet)
training_validation_split: 0.9
